"""
IALA Policy Toolkit — Page 4: Economic Data Dashboard
======================================================
Unified dashboard: select ANZSIC industries at Division (level 1),
Subdivision (level 2), or Group (level 3) granularity, then see all
available indicators — business counts, firm size structure, entry/exit
dynamics, survival rates, and labour share — for that selection.

Data generated by:  python fetch_abs_business_data.py

Sources (in output/):
  abs_division_counts.csv    Entry/exit by division, 2022-2025
  abs_division_survival.csv  4-year survival by division (June 2021 cohort)
  abs_business_counts.csv    Businesses by ANZSIC class, 2024 & 2025
  abs_employment_dist.csv    Employment-size breakdown by class, 2024 & 2025
  abs_wage_share.csv         Labour share by subdivision, 2022-2024
"""

from pathlib import Path
import pandas as pd
import plotly.express as px
import streamlit as st

from utils.auth import check_auth
from utils.pirates import render_pirate_robot

# ── Page config ───────────────────────────────────────────────────────────────

st.set_page_config(
    page_title="Economic Data | IALA Policy Toolkit",
    page_icon="📊",
    layout="wide",
)
check_auth()

DATA_DIR = Path(__file__).parent.parent / "output"


# ════════════════════════════════════════════════════════════════════════════
# DATA LOADING & ENRICHMENT
# ════════════════════════════════════════════════════════════════════════════

@st.cache_data(ttl=3600)
def load_all() -> dict:
    """
    Load all five ABS CSVs and enrich the class-level frames with
    derived subdivision_code and division columns so every frame can
    be filtered at any level of the ANZSIC hierarchy.
    """
    def read(f):
        p = DATA_DIR / f
        return pd.read_csv(p) if p.exists() else pd.DataFrame()

    div_counts   = read("abs_division_counts.csv")
    div_survival = read("abs_division_survival.csv")
    biz_counts   = read("abs_business_counts.csv")
    emp_dist     = read("abs_employment_dist.csv")
    wage_share   = read("abs_wage_share.csv")

    # Build subdivision_code -> division lookup from wage_share
    # (wage_share carries both columns so this is reliable)
    subdiv_to_div: dict[str, str] = {}
    if not wage_share.empty:
        for _, r in wage_share[["subdivision_code","division"]].drop_duplicates().iterrows():
            subdiv_to_div[r["subdivision_code"]] = r["division"]

    # Enrich class-level frames:
    #   anzsic_group_code (3-digit) first 2 chars = subdivision_code
    #   subdivision_code maps to division name via subdiv_to_div
    for df in [biz_counts, emp_dist]:
        if not df.empty:
            df["subdivision_code"] = df["anzsic_group_code"].str[:2]
            df["division"] = df["subdivision_code"].map(subdiv_to_div)

    return dict(
        div_counts=div_counts,
        div_survival=div_survival,
        biz_counts=biz_counts,
        emp_dist=emp_dist,
        wage_share=wage_share,
        subdiv_to_div=subdiv_to_div,
    )


# ════════════════════════════════════════════════════════════════════════════
# HIERARCHY HELPERS
# ════════════════════════════════════════════════════════════════════════════

def build_options(dfs: dict, level: int) -> list[tuple[str, str]]:
    """Return (code, display_label) pairs for the multiselect at the given level."""
    if level == 1:
        dc = dfs["div_counts"]
        if dc.empty:
            return []
        return [(d, d) for d in sorted(dc["division"].unique())]

    if level == 2:
        ws = dfs["wage_share"]
        if ws.empty:
            return []
        rows = (ws[["subdivision_code","subdivision_name","division"]]
                .drop_duplicates()
                .sort_values("subdivision_code"))
        return [
            (r["subdivision_code"],
             f"{r['subdivision_code']} – {r['subdivision_name']}  ({r['division'][:25]}...)")
            for _, r in rows.iterrows()
        ]

    # level == 3: group by anzsic_group_code
    bc = dfs["biz_counts"]
    if bc.empty:
        return []
    latest = bc[bc["year"] == bc["year"].max()]
    grp = (latest.groupby("anzsic_group_code")
           .agg(total=("total_businesses","sum"), n=("anzsic_class_code","count"))
           .reset_index()
           .sort_values("anzsic_group_code"))
    # Representative name: take the first class name in each group
    first_name = bc.groupby("anzsic_group_code")["anzsic_class_name"].first().to_dict()
    return [
        (r["anzsic_group_code"],
         f"{r['anzsic_group_code']} – {first_name.get(r['anzsic_group_code'],'')[:45]}  "
         f"({int(r['total']):,} firms, {int(r['n'])} classes)")
        for _, r in grp.iterrows()
    ]


def filter_dfs(dfs: dict, level: int, codes: list[str]) -> dict:
    """
    Return a dict of DataFrames filtered to the selected ANZSIC codes.

    For levels 2 and 3, division-level frames (div_counts, div_survival)
    are filtered to the parent division(s) and marked with a note so the
    UI can display a 'parent level' caveat.
    """
    empty = {k: pd.DataFrame()
             for k in ["div_counts","div_survival","biz_counts","emp_dist","wage_share"]}
    if not codes:
        return empty

    dc  = dfs["div_counts"].copy()
    ds  = dfs["div_survival"].copy()
    bc  = dfs["biz_counts"].copy()
    ed  = dfs["emp_dist"].copy()
    ws  = dfs["wage_share"].copy()
    s2d = dfs["subdiv_to_div"]

    if level == 1:
        dc = dc[dc["division"].isin(codes)]
        ds = ds[ds["division"].isin(codes)]
        ws = ws[ws["division"].isin(codes)]
        bc = bc[bc["division"].isin(codes)] if "division" in bc.columns else pd.DataFrame()
        ed = ed[ed["division"].isin(codes)] if "division" in ed.columns else pd.DataFrame()

    elif level == 2:
        parent_divs = {s2d[c] for c in codes if c in s2d}
        dc = dc[dc["division"].isin(parent_divs)]
        ds = ds[ds["division"].isin(parent_divs)]
        ws = ws[ws["subdivision_code"].isin(codes)]
        bc = bc[bc["subdivision_code"].isin(codes)] if "subdivision_code" in bc.columns else pd.DataFrame()
        ed = ed[ed["subdivision_code"].isin(codes)] if "subdivision_code" in ed.columns else pd.DataFrame()

    else:  # level 3
        parent_subdivs = {c[:2] for c in codes}
        parent_divs    = {s2d[s] for s in parent_subdivs if s in s2d}
        dc = dc[dc["division"].isin(parent_divs)]
        ds = ds[ds["division"].isin(parent_divs)]
        ws = ws[ws["subdivision_code"].isin(parent_subdivs)]
        bc = bc[bc["anzsic_group_code"].isin(codes)]
        ed = ed[ed["anzsic_group_code"].isin(codes)]

    return dict(div_counts=dc, div_survival=ds, biz_counts=bc,
                emp_dist=ed, wage_share=ws)


# ════════════════════════════════════════════════════════════════════════════
# SIDEBAR
# ════════════════════════════════════════════════════════════════════════════

with st.sidebar:
    st.markdown("### 🏴‍☠️ IALA Policy Toolkit")
    st.markdown("---")
    st.page_link("app.py",                              label="🏠 Home",                     use_container_width=True)
    st.page_link("pages/1_Impact_Analysis_Helper.py",   label="📋 Impact Analysis Helper",   use_container_width=True)
    st.page_link("pages/2_Regulatory_Burden_Helper.py", label="💰 Regulatory Burden Helper", use_container_width=True)
    st.page_link("pages/3_Regulatory_Cost_Analysis.py", label="📊 Regulatory Cost Analysis", use_container_width=True)
    st.page_link("pages/4_Data.py",                     label="📈 Economic Data",             use_container_width=True)
    st.markdown("---")
    render_pirate_robot(location="inline")
    st.markdown("---")

    st.markdown("#### ANZSIC Granularity")
    level_choice = st.radio(
        "Select level",
        options=[1, 2, 3],
        format_func=lambda x: {
            1: "1 – Division  (19 industries)",
            2: "2 – Subdivision  (~81 groups)",
            3: "3 – Group  (~250 groups)",
        }[x],
        index=0,
    )
    st.caption(
        "Level 1: broadest view.  "
        "Level 3: most granular — counts and size at class level, "
        "wage share and survival at parent level."
    )
    st.markdown("---")
    st.caption("Data: ABS 8165.0 + ABS 8155.0.\nRefresh: `python fetch_abs_business_data.py`")


# ════════════════════════════════════════════════════════════════════════════
# LOAD & SELECT
# ════════════════════════════════════════════════════════════════════════════

dfs = load_all()

if all(v.empty for v in dfs.values() if isinstance(v, pd.DataFrame)):
    st.error("No data files found. Run `python fetch_abs_business_data.py` first.")
    st.stop()

options = build_options(dfs, level_choice)
code_list = [c for c, _ in options]
label_map  = {c: lbl for c, lbl in options}

st.title("📈 Economic Data Dashboard")
st.markdown(
    "Choose one or more ANZSIC industries below.  The dashboard assembles "
    "all available indicators for your selection into a single view."
)

selected_codes = st.multiselect(
    f"Select {'Division' if level_choice==1 else 'Subdivision' if level_choice==2 else 'Group'}(s)",
    options=code_list,
    default=code_list[:1] if code_list else [],
    format_func=lambda c: label_map.get(c, c),
    placeholder="Type to search or scroll to browse…",
)

if not selected_codes:
    st.info("Select at least one industry above to generate the dashboard.")
    st.stop()

filt = filter_dfs(dfs, level_choice, selected_codes)
dc = filt["div_counts"]
ds = filt["div_survival"]
bc = filt["biz_counts"]
ed = filt["emp_dist"]
ws = filt["wage_share"]

# Caveat banner for levels 2 & 3 where some frames come from parent levels
if level_choice > 1:
    st.info(
        f"ℹ️ **Entry/exit trend and survival** data is available at Division level only — "
        f"charts show the parent division(s) for your selection.",
        icon="ℹ️",
    )

# ════════════════════════════════════════════════════════════════════════════
# HEADLINE METRIC TILES
# ════════════════════════════════════════════════════════════════════════════

latest_bc_yr = int(bc["year"].max()) if not bc.empty else None
latest_dc_yr = int(dc["year"].max()) if not dc.empty else None
latest_ws_yr = int(ws["year"].max()) if not ws.empty else None

# Total firms — prefer class-level data (more granular); fall back to division
total_firms = avg_entry = avg_exit = avg_surv4 = avg_ls = None

if not bc.empty and latest_bc_yr:
    bc_l = bc[bc["year"] == latest_bc_yr]
    total_firms = int(bc_l["total_businesses"].sum())
    tot = bc_l["total_businesses"].sum()
    if tot > 0:
        avg_entry = (bc_l["entry_rate"] * bc_l["total_businesses"]).sum() / tot
        avg_exit  = (bc_l["exit_rate"]  * bc_l["total_businesses"]).sum() / tot
elif not dc.empty and latest_dc_yr:
    dc_l = dc[dc["year"] == latest_dc_yr]
    total_firms = int(dc_l["op_end"].sum())
    avg_entry   = dc_l["entry_rate"].mean()
    avg_exit    = dc_l["exit_rate"].mean()

if not ds.empty and "surv_rate_4yr" in ds.columns:
    avg_surv4 = ds["surv_rate_4yr"].mean()

if not ws.empty and latest_ws_yr:
    avg_ls = ws[ws["year"] == latest_ws_yr]["labour_share_pct"].mean()

st.markdown("---")
m1, m2, m3, m4, m5 = st.columns(5)
firm_label = f"June {latest_bc_yr or latest_dc_yr}"
with m1:
    st.metric("Total firms", f"{total_firms:,}" if total_firms else "—",
              help=f"Operating businesses at end of FY ({firm_label})")
with m2:
    st.metric("Avg entry rate", f"{avg_entry:.1f}%" if avg_entry else "—",
              help="New businesses as % of businesses at start of year")
with m3:
    st.metric("Avg exit rate", f"{avg_exit:.1f}%" if avg_exit else "—",
              help="Businesses ceasing trading as % of those at start")
with m4:
    st.metric("4-yr survival", f"{avg_surv4:.1f}%" if avg_surv4 else "—",
              help="% of June 2021 cohort still operating in June 2025 (division level)")
with m5:
    yr_lbl = f"{latest_ws_yr-1}–{str(latest_ws_yr)[2:]}" if latest_ws_yr else ""
    st.metric("Labour share", f"{avg_ls:.1f}%" if avg_ls else "—",
              help=f"Wages ÷ Industry Value Added ({yr_lbl})")

st.markdown("---")


# ════════════════════════════════════════════════════════════════════════════
# ROW 1  —  Business counts  |  Firm size structure
# ════════════════════════════════════════════════════════════════════════════

col1, col2 = st.columns(2)

# ── Business counts trend ────────────────────────────────────────────────────
with col1:
    st.subheader("Business Counts Over Time")
    if not dc.empty and "op_end" in dc.columns:
        # If only one division (or user at level 1 with multi), show per-division lines
        if dc["division"].nunique() == 1:
            df_plot = dc.sort_values("year")
            fig = px.line(df_plot, x="year", y="op_end", markers=True,
                          labels={"op_end": "Businesses at year-end", "year": "Year"})
        else:
            fig = px.line(dc.sort_values(["division","year"]),
                          x="year", y="op_end", color="division", markers=True,
                          labels={"op_end": "Businesses at year-end",
                                  "year": "Year", "division": ""})
            fig.update_layout(legend=dict(orientation="h", y=-0.25, font_size=10))
        fig.update_layout(yaxis_tickformat=",", height=340, margin=dict(t=10,b=10))
        st.plotly_chart(fig, use_container_width=True)
        st.caption("Source: ABS 8165.0 DC01 — division level, 2022–2025")

    elif not bc.empty:
        df_plot = bc.groupby("year")["total_businesses"].sum().reset_index()
        fig = px.bar(df_plot, x="year", y="total_businesses",
                     labels={"total_businesses": "Businesses", "year": "Year"},
                     color_discrete_sequence=["#4C72B0"])
        fig.update_layout(yaxis_tickformat=",", height=340, margin=dict(t=10,b=10))
        st.plotly_chart(fig, use_container_width=True)
        st.caption("Source: ABS 8165.0 DC02 — class level, 2024 & 2025 only")
    else:
        st.info("No business count data for this selection.")

# ── Firm size structure ───────────────────────────────────────────────────────
with col2:
    st.subheader("Firm Size Structure")
    size_cols = ["non_employing","emp_1_4","emp_5_19","emp_20_199","emp_200plus"]
    size_labels = {"non_employing":"Non-employing", "emp_1_4":"1–4 emp",
                   "emp_5_19":"5–19 emp", "emp_20_199":"20–199 emp", "emp_200plus":"200+ emp"}

    if not ed.empty:
        yr_opt = sorted(ed["year"].unique(), reverse=True)
        sel_yr = st.radio("Year", yr_opt, horizontal=True, key="size_yr")
        totals = ed[ed["year"] == sel_yr][size_cols].sum()
        df_size = pd.DataFrame({
            "Band":  [size_labels[c] for c in size_cols],
            "Count": [int(totals[c]) for c in size_cols],
        })
        fig = px.pie(df_size, names="Band", values="Count",
                     color_discrete_sequence=px.colors.sequential.Blues[::-1][1:],
                     hole=0.38)
        fig.update_traces(textposition="inside", textinfo="percent+label")
        fig.update_layout(showlegend=False, height=320, margin=dict(t=10,b=10))
        st.plotly_chart(fig, use_container_width=True)
        st.caption(f"Source: ABS 8165.0 DC02 — class level, June {int(sel_yr)}")
    else:
        st.info("No employment size data for this selection.")


# ════════════════════════════════════════════════════════════════════════════
# ROW 2  —  Entry / exit rates  |  Labour share
# ════════════════════════════════════════════════════════════════════════════

col3, col4 = st.columns(2)

# ── Entry / exit rates over time ─────────────────────────────────────────────
with col3:
    st.subheader("Entry & Exit Rates")
    if not dc.empty and "entry_rate" in dc.columns:
        if dc["division"].nunique() == 1:
            df_er = dc.sort_values("year")
            fig = px.line(
                df_er.melt(id_vars="year", value_vars=["entry_rate","exit_rate"],
                           var_name="metric", value_name="rate"),
                x="year", y="rate", color="metric", markers=True,
                labels={"rate": "Rate (%)", "year": "Year", "metric": ""},
                color_discrete_map={"entry_rate":"#2ca02c","exit_rate":"#d62728"},
            )
        else:
            # Average across selected divisions (weighted by op_end)
            df_er = (dc.groupby("year")
                     .apply(lambda g: pd.Series({
                         "entry_rate": (g["entry_rate"] * g["op_end"]).sum() / g["op_end"].sum(),
                         "exit_rate":  (g["exit_rate"]  * g["op_end"]).sum() / g["op_end"].sum(),
                     }))
                     .reset_index())
            fig = px.line(
                df_er.melt(id_vars="year", value_vars=["entry_rate","exit_rate"],
                           var_name="metric", value_name="rate"),
                x="year", y="rate", color="metric", markers=True,
                labels={"rate": "Rate (%)", "year": "Year", "metric": ""},
                color_discrete_map={"entry_rate":"#2ca02c","exit_rate":"#d62728"},
            )
        fig.update_layout(height=340, margin=dict(t=10,b=10))
        st.plotly_chart(fig, use_container_width=True)
        if level_choice > 1:
            st.caption("⚠️ Rates shown at parent division level")
        else:
            st.caption("Source: ABS 8165.0 DC01, 2022–2025")
    else:
        st.info("No entry/exit rate data for this selection.")

# ── Labour share trend ────────────────────────────────────────────────────────
with col4:
    st.subheader("Labour Share  (Wages ÷ IVA)")
    if not ws.empty and "labour_share_pct" in ws.columns:
        # Colour by subdivision if ≤10 lines, else aggregate to division
        n_subdivs = ws["subdivision_name"].nunique()
        if n_subdivs <= 10:
            df_ls = ws.sort_values(["subdivision_name","year"])
            colour_col = "subdivision_name"
        else:
            df_ls = (ws.groupby(["division","year"])
                     .agg(labour_share_pct=("labour_share_pct","mean"))
                     .reset_index())
            colour_col = "division"

        fig = px.line(df_ls, x="year", y="labour_share_pct",
                      color=colour_col, markers=True,
                      labels={"labour_share_pct":"Labour share (%)",
                              "year":"Year", colour_col:""},)
        fig.add_hline(y=50, line_dash="dot", line_color="lightgrey",
                      annotation_text="50%")
        fig.update_layout(yaxis_range=[0,100], height=340,
                          margin=dict(t=10,b=10), legend_title="")
        st.plotly_chart(fig, use_container_width=True)
        note = "(subdivision level)" if n_subdivs <= 10 else "(averaged to division)"
        lvl_note = " — parent subdivision" if level_choice == 3 else ""
        st.caption(f"Source: ABS 8155.0 DO001, 2022–2024 {note}{lvl_note}")
    else:
        st.info("No labour share data for this selection.")


# ════════════════════════════════════════════════════════════════════════════
# ROW 3  —  Survival curve  (full width)
# ════════════════════════════════════════════════════════════════════════════

st.subheader("Business Survival — June 2021 Cohort")

surv_cols = ["surv_rate_1yr","surv_rate_2yr","surv_rate_3yr","surv_rate_4yr"]
if not ds.empty and all(c in ds.columns for c in surv_cols):
    if level_choice > 1:
        st.caption("⚠️ Survival data is only published at Division level — showing parent division(s).")

    df_sm = ds.melt(id_vars=["division"], value_vars=surv_cols,
                    var_name="period", value_name="survival_pct")
    df_sm["years"] = df_sm["period"].str.extract(r"(\d+)yr").astype(int)

    if ds["division"].nunique() == 1:
        fig = px.line(df_sm.sort_values("years"), x="years", y="survival_pct",
                      markers=True,
                      labels={"years":"Years since June 2021","survival_pct":"% surviving"})
        fig.update_traces(line_color="#1f77b4", line_width=2.5)
    else:
        fig = px.line(df_sm.sort_values(["division","years"]),
                      x="years", y="survival_pct",
                      color="division", markers=True,
                      labels={"years":"Years since June 2021","survival_pct":"% surviving",
                              "division":""})
        fig.update_layout(legend=dict(orientation="h", y=-0.2, font_size=10))

    fig.update_layout(xaxis=dict(tickvals=[1,2,3,4]),
                      yaxis_range=[0,100], height=360)
    st.plotly_chart(fig, use_container_width=True)
    st.caption("Source: ABS 8165.0 DC01 Table 2 — cohort of firms operating at June 2021, "
               "tracked to June 2025")
else:
    st.info("No survival data for this selection.")


# ════════════════════════════════════════════════════════════════════════════
# DETAILED DATA TABLES
# ════════════════════════════════════════════════════════════════════════════

with st.expander("📋 Detailed data tables"):
    t1, t2, t3, t4 = st.tabs(
        ["Division Counts", "Business Counts (Class)", "Employment Size", "Labour Share"]
    )
    with t1:
        if not dc.empty:
            st.dataframe(dc.sort_values(["division","year"]), use_container_width=True)
        else:
            st.info("No data for selection.")
    with t2:
        if not bc.empty:
            st.dataframe(bc.sort_values(["anzsic_class_code","year"]), use_container_width=True)
        else:
            st.info("No data for selection.")
    with t3:
        if not ed.empty:
            st.dataframe(ed.sort_values(["anzsic_class_code","year"]), use_container_width=True)
        else:
            st.info("No data for selection.")
    with t4:
        if not ws.empty:
            show = ["division","subdivision_code","subdivision_name","year",
                    "wages_m","iva_m","employment_000","labour_share_pct"]
            st.dataframe(ws[[c for c in show if c in ws.columns]]
                         .sort_values(["subdivision_name","year"]),
                         use_container_width=True)
        else:
            st.info("No data for selection.")


# ── Footer ────────────────────────────────────────────────────────────────────

st.markdown("---")
st.caption(
    "Data: ABS 8165.0 Counts of Australian Businesses (June 2021–2025) and "
    "ABS 8155.0 Australian Industry (2023-24).  "
    "Run `python fetch_abs_business_data.py` to refresh from local ABS Data Manual/ files."
)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       