"""
IALA Policy Toolkit — Page 4: Economic Data Dashboard
======================================================
Select ANZSIC industries at the top of the page, then see:
  1. Snapshot — latest value of every indicator + direction + interpretation
  2. Data Explorer — time series and breakdowns for deeper investigation

Data generated by:  python fetch_abs_business_data.py
"""

from pathlib import Path
import pandas as pd
import plotly.express as px
import streamlit as st

from utils.auth import check_auth
from utils.pirates import render_pirate_robot

st.set_page_config(
    page_title="Economic Data | IALA Policy Toolkit",
    page_icon="📊",
    layout="wide",
)
check_auth()

DATA_DIR = Path(__file__).parent.parent / "output"


# ════════════════════════════════════════════════════════════════════════════
# DATA LOADING
# ════════════════════════════════════════════════════════════════════════════

@st.cache_data(ttl=3600)
def load_all() -> dict:
    def read(f):
        p = DATA_DIR / f
        return pd.read_csv(p) if p.exists() else pd.DataFrame()

    dc = read("abs_division_counts.csv")
    ds = read("abs_division_survival.csv")
    bc = read("abs_business_counts.csv")
    ed = read("abs_employment_dist.csv")
    ws = read("abs_wage_share.csv")

    subdiv_to_div: dict = {}
    if not ws.empty:
        for _, r in ws[["subdivision_code","division"]].drop_duplicates().iterrows():
            subdiv_to_div[r["subdivision_code"]] = r["division"]

    for df in [bc, ed]:
        if not df.empty:
            df["subdivision_code"] = df["anzsic_group_code"].str[:2]
            df["division"] = df["subdivision_code"].map(subdiv_to_div)

    return dict(div_counts=dc, div_survival=ds, biz_counts=bc,
                emp_dist=ed, wage_share=ws, subdiv_to_div=subdiv_to_div)


def build_options(dfs: dict, level: int) -> list:
    if level == 1:
        dc = dfs["div_counts"]
        return [] if dc.empty else [(d, d) for d in sorted(dc["division"].unique())]
    if level == 2:
        ws = dfs["wage_share"]
        if ws.empty:
            return []
        rows = ws[["subdivision_code","subdivision_name","division"]].drop_duplicates().sort_values("subdivision_code")
        return [(r["subdivision_code"],
                 f"{r['subdivision_code']} – {r['subdivision_name']}  ({r['division'][:22]}…)")
                for _, r in rows.iterrows()]
    bc = dfs["biz_counts"]
    if bc.empty:
        return []
    latest = bc[bc["year"] == bc["year"].max()]
    grp = (latest.groupby("anzsic_group_code")
           .agg(total=("total_businesses","sum"), n=("anzsic_class_code","count"))
           .reset_index().sort_values("anzsic_group_code"))
    first_name = bc.groupby("anzsic_group_code")["anzsic_class_name"].first().to_dict()
    return [(r["anzsic_group_code"],
             f"{r['anzsic_group_code']} – {first_name.get(r['anzsic_group_code'],'')[:40]}  "
             f"({int(r['total']):,} firms)")
            for _, r in grp.iterrows()]


def filter_dfs(dfs: dict, level: int, codes: list) -> dict:
    empty = {k: pd.DataFrame()
             for k in ["div_counts","div_survival","biz_counts","emp_dist","wage_share"]}
    if not codes:
        return empty
    dc, ds, bc, ed, ws = (dfs[k].copy() for k in
                          ["div_counts","div_survival","biz_counts","emp_dist","wage_share"])
    s2d = dfs["subdiv_to_div"]
    if level == 1:
        dc = dc[dc["division"].isin(codes)]
        ds = ds[ds["division"].isin(codes)]
        ws = ws[ws["division"].isin(codes)]
        bc = bc[bc["division"].isin(codes)] if "division" in bc.columns else pd.DataFrame()
        ed = ed[ed["division"].isin(codes)] if "division" in ed.columns else pd.DataFrame()
    elif level == 2:
        pdivs = {s2d[c] for c in codes if c in s2d}
        dc = dc[dc["division"].isin(pdivs)]
        ds = ds[ds["division"].isin(pdivs)]
        ws = ws[ws["subdivision_code"].isin(codes)]
        bc = bc[bc["subdivision_code"].isin(codes)] if "subdivision_code" in bc.columns else pd.DataFrame()
        ed = ed[ed["subdivision_code"].isin(codes)] if "subdivision_code" in ed.columns else pd.DataFrame()
    else:
        psubs = {c[:2] for c in codes}
        pdivs = {s2d[s] for s in psubs if s in s2d}
        dc = dc[dc["division"].isin(pdivs)]
        ds = ds[ds["division"].isin(pdivs)]
        ws = ws[ws["subdivision_code"].isin(psubs)]
        bc = bc[bc["anzsic_group_code"].isin(codes)]
        ed = ed[ed["anzsic_group_code"].isin(codes)]
    return dict(div_counts=dc, div_survival=ds, biz_counts=bc, emp_dist=ed, wage_share=ws)


# ════════════════════════════════════════════════════════════════════════════
# SNAPSHOT HELPERS
# ════════════════════════════════════════════════════════════════════════════

def _delta_str(val, prev):
    """Format a numeric delta with sign, or None if unavailable."""
    if val is None or prev is None or prev == 0:
        return None
    return round(val - prev, 1)


def _pct_delta(val, prev):
    if val is None or prev is None or prev == 0:
        return None
    return f"{val - prev:+.1f} pp"   # percentage-point change


def _count_delta(val, prev):
    if val is None or prev is None:
        return None
    d = int(val - prev)
    return f"{d:+,}"


def _interp(metric: str, value, delta) -> tuple[str, str]:
    """
    Return (short interpretation, colour hint: 'normal'|'good'|'warn'|'neutral').
    delta is the year-on-year change (positive = went up).
    """
    if value is None:
        return "No data", "neutral"

    if metric == "entry_rate":
        level_txt = "High" if value > 15 else "Moderate" if value > 8 else "Low"
        if delta is None:
            return f"{level_txt} rate of new entrants", "neutral"
        dir_txt = "rising ↑" if delta > 0.5 else "falling ↓" if delta < -0.5 else "stable →"
        if value < 8 and delta < 0:
            return f"Low & falling — investigate barriers to entry", "warn"
        if value > 15:
            return f"High — market is highly contestable", "good"
        return f"{level_txt} new-entrant activity, {dir_txt}", "neutral"

    if metric == "exit_rate":
        if delta is None:
            return "Measures firms ceasing trading", "neutral"
        dir_txt = "rising ↑" if delta > 0.5 else "falling ↓" if delta < -0.5 else "stable →"
        return f"Exit rate {dir_txt}", "neutral"

    if metric == "net_entry":
        if value > 2:
            return "Growing — more entrants than exits", "good"
        if value < -2:
            return "Contracting — exits exceeding entries", "warn"
        return "Roughly balanced entry and exit", "neutral"

    if metric == "total_firms":
        if delta is None:
            return "Total actively trading businesses", "neutral"
        dir_txt = "grew" if delta > 0 else "shrank"
        return f"Firm count {dir_txt} year-on-year", "good" if delta > 0 else "warn"

    if metric == "labour_share":
        level_txt = "High (labour-intensive)" if value > 60 else \
                    "Low (capital-intensive)" if value < 30 else "Moderate"
        if delta is None:
            return f"{level_txt}", "neutral"
        if delta < -2:
            return f"Declining ↓ — profits capturing more value; possible market power signal", "warn"
        if delta > 2:
            return f"Rising ↑ — labour capturing more of value added", "good"
        return f"{level_txt}, broadly stable", "neutral"

    if metric == "survival_4yr":
        if value > 75:
            return "Most businesses survive 4 years — stable industry", "neutral"
        if value > 60:
            return "Moderate survival — typical of competitive markets", "neutral"
        return "Lower survival — competitive pressure or difficult conditions", "warn"

    if metric == "non_emp_share":
        if value > 70:
            return "Dominated by sole traders / non-employing businesses", "neutral"
        if delta is not None and delta > 3:
            return "Non-employing share rising — possible fragmentation", "neutral"
        return "Mix of employing and non-employing businesses", "neutral"

    return "", "neutral"


def _metric_card(label: str, value_str: str, delta_str, interp: str, colour: str):
    """Render a metric with delta and interpretation caption."""
    delta_kwargs = {"delta": delta_str} if delta_str else {}
    st.metric(label=label, value=value_str, **delta_kwargs)
    icon = "✅" if colour == "good" else "⚠️" if colour == "warn" else "ℹ️"
    if interp:
        st.caption(f"{icon} {interp}")


# ════════════════════════════════════════════════════════════════════════════
# SIDEBAR (navigation only)
# ════════════════════════════════════════════════════════════════════════════

with st.sidebar:
    st.markdown("### 🏴‍☠️ IALA Policy Toolkit")
    st.markdown("---")
    st.page_link("app.py",                              label="🏠 Home",                     use_container_width=True)
    st.page_link("pages/1_Impact_Analysis_Helper.py",   label="📋 Impact Analysis Helper",   use_container_width=True)
    st.page_link("pages/2_Regulatory_Burden_Helper.py", label="💰 Regulatory Burden Helper", use_container_width=True)
    st.page_link("pages/3_Regulatory_Cost_Analysis.py", label="📊 Regulatory Cost Analysis", use_container_width=True)
    st.page_link("pages/4_Data.py",                     label="📈 Economic Data",             use_container_width=True)
    st.markdown("---")
    render_pirate_robot(location="inline")
    st.markdown("---")
    st.caption("Data: ABS 8165.0 + ABS 8155.0\nRefresh: `python fetch_abs_business_data.py`")


# ════════════════════════════════════════════════════════════════════════════
# PAGE HEADER + SELECTOR
# ════════════════════════════════════════════════════════════════════════════

st.title("📈 Economic Data Dashboard")
st.markdown(
    "Select one or more ANZSIC industries below. "
    "The page reports the latest value of every collected indicator, "
    "whether it is trending up or down, and what that means for competition policy."
)

dfs = load_all()
if all(v.empty for v in dfs.values() if isinstance(v, pd.DataFrame)):
    st.error("No data files found. Run `python fetch_abs_business_data.py` first.")
    st.stop()

# ── Selector row ──────────────────────────────────────────────────────────────
sel_col1, sel_col2 = st.columns([1, 3])
with sel_col1:
    level_choice = st.radio(
        "**ANZSIC level**",
        options=[1, 2, 3],
        format_func=lambda x: {1:"1 – Division (19)",
                                2:"2 – Subdivision (~81)",
                                3:"3 – Group (~250)"}[x],
        index=0,
    )
with sel_col2:
    options   = build_options(dfs, level_choice)
    code_list = [c for c, _ in options]
    label_map = {c: lbl for c, lbl in options}
    selected_codes = st.multiselect(
        f"**Select {'Division' if level_choice==1 else 'Subdivision' if level_choice==2 else 'Group'}(s)**",
        options=code_list,
        default=code_list[:1] if code_list else [],
        format_func=lambda c: label_map.get(c, c),
        placeholder="Type to search…",
    )

if not selected_codes:
    st.info("Select at least one industry above.")
    st.stop()

filt = filter_dfs(dfs, level_choice, selected_codes)
dc = filt["div_counts"]
ds = filt["div_survival"]
bc = filt["biz_counts"]
ed = filt["emp_dist"]
ws = filt["wage_share"]

# ── Availability note for sub-division selections ────────────────────────────
if level_choice > 1:
    st.caption(
        "ℹ️ Entry/exit trend and survival are published at Division level only — "
        "those indicators show the parent division(s)."
    )

st.divider()


# ════════════════════════════════════════════════════════════════════════════
# COMPUTE ALL METRICS
# ════════════════════════════════════════════════════════════════════════════

# ── Helper: get weighted average of a rate column for a given year ────────────
def wavg(df, val_col, wt_col, year):
    sub = df[df["year"] == year].dropna(subset=[val_col, wt_col])
    if sub.empty or sub[wt_col].sum() == 0:
        return None
    return (sub[val_col] * sub[wt_col]).sum() / sub[wt_col].sum()


def simple_avg(df, val_col, year):
    sub = df[df["year"] == year][val_col].dropna()
    return sub.mean() if not sub.empty else None


# Business counts (prefer class-level, fall back to division)
latest_bc_yr = int(bc["year"].max()) if not bc.empty else None
prev_bc_yr   = int(bc["year"].min()) if (not bc.empty and bc["year"].nunique() > 1) else None

latest_dc_yr = int(dc["year"].max()) if not dc.empty else None
prev_dc_yr   = (sorted(dc["year"].unique())[-2]
                if (not dc.empty and dc["year"].nunique() > 1) else None)

latest_ws_yr = int(ws["year"].max()) if not ws.empty else None
prev_ws_yr   = (sorted(ws["year"].unique())[-2]
                if (not ws.empty and ws["year"].nunique() > 1) else None)

# Total firms
if not bc.empty and latest_bc_yr:
    total_firms_now  = int(bc[bc["year"]==latest_bc_yr]["total_businesses"].sum())
    total_firms_prev = (int(bc[bc["year"]==prev_bc_yr]["total_businesses"].sum())
                        if prev_bc_yr else None)
    firms_src_yr = latest_bc_yr
elif not dc.empty and latest_dc_yr:
    total_firms_now  = int(dc[dc["year"]==latest_dc_yr]["op_end"].sum())
    total_firms_prev = (int(dc[dc["year"]==prev_dc_yr]["op_end"].sum())
                        if prev_dc_yr else None)
    firms_src_yr = latest_dc_yr
else:
    total_firms_now = total_firms_prev = firms_src_yr = None

# Entry rate  (weighted by businesses, division level)
entry_now  = wavg(dc, "entry_rate", "op_end", latest_dc_yr) if not dc.empty and latest_dc_yr else None
entry_prev = wavg(dc, "entry_rate", "op_end", prev_dc_yr)   if not dc.empty and prev_dc_yr  else None

# Exit rate
exit_now  = wavg(dc, "exit_rate", "op_end", latest_dc_yr) if not dc.empty and latest_dc_yr else None
exit_prev = wavg(dc, "exit_rate", "op_end", prev_dc_yr)   if not dc.empty and prev_dc_yr  else None

# Net entry = entry_rate - exit_rate
net_now  = (entry_now  - exit_now)  if entry_now  and exit_now  else None
net_prev = (entry_prev - exit_prev) if entry_prev and exit_prev else None

# 4-year survival (no trend; single cohort value)
surv4_now = ds["surv_rate_4yr"].mean() if not ds.empty and "surv_rate_4yr" in ds.columns else None

# Labour share (subdivision weighted by IVA)
ls_now  = wavg(ws, "labour_share_pct", "iva_m", latest_ws_yr) if not ws.empty and latest_ws_yr else None
ls_prev = wavg(ws, "labour_share_pct", "iva_m", prev_ws_yr)   if not ws.empty and prev_ws_yr  else None

# Non-employing share (% of firms that are sole traders / non-employing)
def non_emp_share(df, yr):
    sub = df[df["year"] == yr]
    if sub.empty or "non_employing" not in sub.columns:
        return None
    tot = sub["total_businesses"].sum()
    return sub["non_employing"].sum() / tot * 100 if tot > 0 else None

ne_now  = non_emp_share(ed, latest_bc_yr) if not ed.empty and latest_bc_yr else None
ne_prev = non_emp_share(ed, prev_bc_yr)   if not ed.empty and prev_bc_yr   else None


# ════════════════════════════════════════════════════════════════════════════
# SECTION 1 — SNAPSHOT
# ════════════════════════════════════════════════════════════════════════════

st.subheader("📊 Industry Snapshot")
st.caption(
    "Latest values with year-on-year change (▲▼) and competition-policy interpretation. "
    f"Entry/exit/survival: ABS 8165.0 division level.  "
    f"Labour share: ABS 8155.0 subdivision level."
)

# ── Row 1: Firm count · Entry rate · Exit rate · Net entry ───────────────────
r1c1, r1c2, r1c3, r1c4 = st.columns(4)

with r1c1:
    interp, col = _interp("total_firms", total_firms_now,
                          (total_firms_now - total_firms_prev) if total_firms_prev else None)
    _metric_card(
        f"Total businesses ({firms_src_yr or '—'})",
        f"{total_firms_now:,}" if total_firms_now else "—",
        _count_delta(total_firms_now, total_firms_prev),
        interp, col,
    )

with r1c2:
    d = _delta_str(entry_now, entry_prev)
    interp, col = _interp("entry_rate", entry_now, d)
    _metric_card(
        f"Entry rate ({latest_dc_yr or '—'})",
        f"{entry_now:.1f}%" if entry_now else "—",
        _pct_delta(entry_now, entry_prev),
        interp, col,
    )

with r1c3:
    d = _delta_str(exit_now, exit_prev)
    interp, col = _interp("exit_rate", exit_now, d)
    _metric_card(
        f"Exit rate ({latest_dc_yr or '—'})",
        f"{exit_now:.1f}%" if exit_now else "—",
        _pct_delta(exit_now, exit_prev),
        interp, col,
    )

with r1c4:
    d = _delta_str(net_now, net_prev)
    interp, col = _interp("net_entry", net_now, d)
    _metric_card(
        f"Net entry  (entry − exit)",
        f"{net_now:+.1f} pp" if net_now is not None else "—",
        _pct_delta(net_now, net_prev),
        interp, col,
    )

# ── Row 2: Labour share · 4-yr survival · Non-employing share ────────────────
st.markdown("")   # spacer
r2c1, r2c2, r2c3, r2c4 = st.columns(4)

with r2c1:
    d = _delta_str(ls_now, ls_prev)
    interp, col = _interp("labour_share", ls_now, d)
    yr_lbl = f"{latest_ws_yr-1}–{str(latest_ws_yr)[2:]}" if latest_ws_yr else "—"
    _metric_card(
        f"Labour share  ({yr_lbl})",
        f"{ls_now:.1f}%" if ls_now else "—",
        _pct_delta(ls_now, ls_prev),
        interp, col,
    )

with r2c2:
    interp, col = _interp("survival_4yr", surv4_now, None)
    _metric_card(
        "4-year survival  (Jun 2021 cohort)",
        f"{surv4_now:.1f}%" if surv4_now else "—",
        None,
        interp, col,
    )

with r2c3:
    d = _delta_str(ne_now, ne_prev)
    interp, col = _interp("non_emp_share", ne_now, d)
    _metric_card(
        f"Non-employing share  ({latest_bc_yr or '—'})",
        f"{ne_now:.1f}%" if ne_now else "—",
        _pct_delta(ne_now, ne_prev),
        interp, col,
    )

with r2c4:
    # Dominant size band
    if not ed.empty and latest_bc_yr:
        size_cols = ["non_employing","emp_1_4","emp_5_19","emp_20_199","emp_200plus"]
        size_labels = {"non_employing":"Non-employing","emp_1_4":"1–4 emp",
                       "emp_5_19":"5–19 emp","emp_20_199":"20–199 emp","emp_200plus":"200+ emp"}
        totals = ed[ed["year"]==latest_bc_yr][size_cols].sum()
        dominant = totals.idxmax()
        dom_pct  = totals[dominant] / totals.sum() * 100
        st.metric(f"Dominant size band ({latest_bc_yr})", size_labels[dominant],
                  delta=f"{dom_pct:.0f}% of firms")
        st.caption("ℹ️ Largest single employment-size category")
    else:
        st.metric("Dominant size band", "—")

st.divider()


# ════════════════════════════════════════════════════════════════════════════
# SECTION 2 — DATA EXPLORER
# ════════════════════════════════════════════════════════════════════════════

st.subheader("🔍 Data Explorer")

tab_counts, tab_entry, tab_size, tab_surv, tab_ls = st.tabs([
    "Business Counts",
    "Entry & Exit",
    "Firm Size",
    "Survival",
    "Labour Share",
])

# ── Business Counts ───────────────────────────────────────────────────────────
with tab_counts:
    if not dc.empty and "op_end" in dc.columns:
        if dc["division"].nunique() == 1:
            fig = px.line(dc.sort_values("year"), x="year", y="op_end", markers=True,
                          labels={"op_end":"Businesses at year-end","year":"Year"})
        else:
            fig = px.line(dc.sort_values(["division","year"]),
                          x="year", y="op_end", color="division", markers=True,
                          labels={"op_end":"Businesses at year-end","year":"Year","division":""})
            fig.update_layout(legend=dict(orientation="h", y=-0.3, font_size=10))
        fig.update_layout(yaxis_tickformat=",", height=380)
        st.plotly_chart(fig, use_container_width=True)
        st.caption("ABS 8165.0 DC01 — division level, 2022–2025")
    elif not bc.empty:
        df_plot = bc.groupby("year")["total_businesses"].sum().reset_index()
        fig = px.bar(df_plot, x="year", y="total_businesses",
                     labels={"total_businesses":"Businesses","year":"Year"},
                     color_discrete_sequence=["#4C72B0"])
        fig.update_layout(yaxis_tickformat=",", height=380)
        st.plotly_chart(fig, use_container_width=True)
        st.caption("ABS 8165.0 DC02 — class level, 2024 & 2025 only")
    else:
        st.info("No business count data for this selection.")

# ── Entry & Exit Rates ────────────────────────────────────────────────────────
with tab_entry:
    if not dc.empty and "entry_rate" in dc.columns:
        col_a, col_b = st.columns(2)
        with col_a:
            if dc["division"].nunique() == 1:
                df_er = dc.sort_values("year")
                fig = px.line(
                    df_er.melt(id_vars="year", value_vars=["entry_rate","exit_rate"],
                               var_name="metric", value_name="rate"),
                    x="year", y="rate", color="metric", markers=True,
                    labels={"rate":"Rate (%)","year":"Year","metric":""},
                    color_discrete_map={"entry_rate":"#2ca02c","exit_rate":"#d62728"},
                )
            else:
                df_agg = (dc.groupby("year")
                          .apply(lambda g: pd.Series({
                              "entry_rate": (g["entry_rate"]*g["op_end"]).sum()/g["op_end"].sum(),
                              "exit_rate":  (g["exit_rate"] *g["op_end"]).sum()/g["op_end"].sum(),
                          })).reset_index())
                fig = px.line(
                    df_agg.melt(id_vars="year", value_vars=["entry_rate","exit_rate"],
                                var_name="metric", value_name="rate"),
                    x="year", y="rate", color="metric", markers=True,
                    labels={"rate":"Rate (%)","year":"Year","metric":""},
                    color_discrete_map={"entry_rate":"#2ca02c","exit_rate":"#d62728"},
                )
            fig.update_layout(height=360, title="Entry & Exit Rates Over Time")
            st.plotly_chart(fig, use_container_width=True)
        with col_b:
            # Latest year: entry vs exit scatter by division
            dc_l = dc[dc["year"] == latest_dc_yr]
            fig2 = px.scatter(
                dc_l, x="entry_rate", y="exit_rate", text="division",
                size="op_end", size_max=30,
                labels={"entry_rate":"Entry rate (%)","exit_rate":"Exit rate (%)"},
                title=f"Contestability Map — FY {latest_dc_yr-1}–{str(latest_dc_yr)[2:]}",
            )
            fig2.add_shape(type="line", x0=0, y0=0, x1=35, y1=35,
                           line=dict(dash="dot", color="grey"))
            fig2.update_traces(textposition="top center", textfont_size=8)
            fig2.update_layout(height=360)
            st.plotly_chart(fig2, use_container_width=True)
        if level_choice > 1:
            st.caption("⚠️ Entry/exit rates shown at parent division level.")
    else:
        st.info("No entry/exit data for this selection.")

# ── Firm Size ─────────────────────────────────────────────────────────────────
with tab_size:
    size_cols = ["non_employing","emp_1_4","emp_5_19","emp_20_199","emp_200plus"]
    size_labels_map = {"non_employing":"Non-employing","emp_1_4":"1–4 emp",
                       "emp_5_19":"5–19 emp","emp_20_199":"20–199 emp","emp_200plus":"200+ emp"}
    if not ed.empty:
        col_a, col_b = st.columns(2)
        yr_opts = sorted(ed["year"].unique(), reverse=True)
        with col_a:
            sel_yr = st.radio("Year", yr_opts, horizontal=True, key="size_yr2")
            totals = ed[ed["year"]==sel_yr][size_cols].sum()
            df_sz = pd.DataFrame({"Band":[size_labels_map[c] for c in size_cols],
                                  "Count":[int(totals[c]) for c in size_cols]})
            fig = px.pie(df_sz, names="Band", values="Count",
                         color_discrete_sequence=px.colors.sequential.Blues[::-1][1:], hole=0.38)
            fig.update_traces(textposition="inside", textinfo="percent+label")
            fig.update_layout(showlegend=False, height=340, title=f"Size mix — June {int(sel_yr)}")
            st.plotly_chart(fig, use_container_width=True)
        with col_b:
            # Stacked bar comparing both years
            df_all = ed.groupby("year")[size_cols].sum().reset_index()
            df_melt = df_all.melt(id_vars="year", value_vars=size_cols,
                                  var_name="band", value_name="count")
            df_melt["label"] = df_melt["band"].map(size_labels_map)
            fig2 = px.bar(df_melt, x="year", y="count", color="label",
                          barmode="stack",
                          labels={"count":"Businesses","year":"Year","label":"Size band"},
                          title="Size structure over time",
                          color_discrete_sequence=px.colors.sequential.Blues[1:])
            fig2.update_layout(yaxis_tickformat=",", height=340, legend_title="")
            st.plotly_chart(fig2, use_container_width=True)
        st.caption("ABS 8165.0 DC02 — class level")
    else:
        st.info("No firm size data for this selection.")

# ── Survival ──────────────────────────────────────────────────────────────────
with tab_surv:
    surv_rate_cols = ["surv_rate_1yr","surv_rate_2yr","surv_rate_3yr","surv_rate_4yr"]
    if not ds.empty and all(c in ds.columns for c in surv_rate_cols):
        if level_choice > 1:
            st.caption("⚠️ Survival is published at Division level — showing parent division(s).")
        df_sm = ds.melt(id_vars=["division"], value_vars=surv_rate_cols,
                        var_name="period", value_name="survival_pct")
        df_sm["years"] = df_sm["period"].str.extract(r"(\d+)yr").astype(int)
        if ds["division"].nunique() == 1:
            fig = px.line(df_sm.sort_values("years"), x="years", y="survival_pct",
                          markers=True,
                          labels={"years":"Years since June 2021","survival_pct":"% surviving"})
            fig.update_traces(line_color="#1f77b4", line_width=2.5)
        else:
            fig = px.line(df_sm.sort_values(["division","years"]),
                          x="years", y="survival_pct", color="division", markers=True,
                          labels={"years":"Years since June 2021","survival_pct":"% surviving",
                                  "division":""})
            fig.update_layout(legend=dict(orientation="h", y=-0.25, font_size=10))
        fig.update_layout(xaxis=dict(tickvals=[1,2,3,4]), yaxis_range=[0,100], height=400)
        st.plotly_chart(fig, use_container_width=True)
        st.caption("ABS 8165.0 DC01 Table 2 — cohort of businesses operating June 2021, trac