"""
IALA Policy Toolkit — Page 4: Economic Data Explorer
=====================================================
Displays public ABS data on Australian business structure and competitive
dynamics by ANZSIC industry.

Data is generated by running:
  python fetch_abs_business_data.py

Source files (in output/):
  abs_division_counts.csv    Entry/exit counts by division, 2022-2025
  abs_division_survival.csv  4-year survival rates by division (June 2021 cohort)
  abs_business_counts.csv    Total businesses by ANZSIC class, 2024 & 2025
  abs_employment_dist.csv    Employment-size breakdown by ANZSIC class
  abs_wage_share.csv         Labour share (wages / IVA) by subdivision, 2022-2024
"""

from pathlib import Path
import pandas as pd
import plotly.express as px
import streamlit as st

from utils.auth import check_auth
from utils.pirates import render_pirate_robot

# ── Page config ──────────────────────────────────────────────────────────────

st.set_page_config(
    page_title="Economic Data | IALA Policy Toolkit",
    page_icon="📊",
    layout="wide",
)
check_auth()

# ── Data directory ────────────────────────────────────────────────────────────

DATA_DIR = Path(__file__).parent.parent / "output"

# Full ANZSIC division names — used for sidebar filter and matching the
# 'division' column in abs_division_counts.csv, abs_division_survival.csv,
# and abs_wage_share.csv
DIVISIONS = [
    "Agriculture, Forestry and Fishing",
    "Mining",
    "Manufacturing",
    "Electricity, Gas, Water and Waste Services",
    "Construction",
    "Wholesale Trade",
    "Retail Trade",
    "Accommodation and Food Services",
    "Transport, Postal and Warehousing",
    "Information Media and Telecommunications",
    "Financial and Insurance Services",
    "Rental, Hiring and Real Estate Services",
    "Professional, Scientific and Technical Services",
    "Administrative and Support Services",
    "Public Administration and Safety",
    "Education and Training",
    "Health Care and Social Assistance",
    "Arts and Recreation Services",
    "Other Services",
]


# ── Data loaders ─────────────────────────────────────────────────────────────

@st.cache_data(ttl=3600)
def load_csv(filename: str) -> pd.DataFrame:
    """Load a CSV from output/; return empty DataFrame if file is missing."""
    path = DATA_DIR / filename
    if not path.exists():
        return pd.DataFrame()
    return pd.read_csv(path)


# ── Sidebar ───────────────────────────────────────────────────────────────────

with st.sidebar:
    st.markdown("### 🏴‍☠️ IALA Policy Toolkit")
    st.markdown("---")
    st.page_link("app.py",                                label="🏠 Home",                     use_container_width=True)
    st.page_link("pages/1_Impact_Analysis_Helper.py",     label="📋 Impact Analysis Helper",   use_container_width=True)
    st.page_link("pages/2_Regulatory_Burden_Helper.py",   label="💰 Regulatory Burden Helper", use_container_width=True)
    st.page_link("pages/3_Regulatory_Cost_Analysis.py",   label="📊 Regulatory Cost Analysis", use_container_width=True)
    st.page_link("pages/4_Data.py",                       label="📈 Economic Data",             use_container_width=True)
    st.markdown("---")
    render_pirate_robot(location="inline")
    st.markdown("---")

    st.markdown("#### Filter by Division")
    div_options = ["All divisions"] + DIVISIONS
    selected_div = st.selectbox("ANZSIC Division", options=div_options,
                                help="Narrows the division-level charts to one industry.")
    active_div = None if selected_div == "All divisions" else selected_div

    st.markdown("---")
    st.caption(
        "Data: ABS 8165.0 (business counts) and ABS 8155.0 (industry). "
        "Refresh: `python fetch_abs_business_data.py`"
    )

# ── Page header ───────────────────────────────────────────────────────────────

st.title("📈 Economic Data Explorer")
st.markdown(
    "Public ABS data on Australian business structure and competitive dynamics "
    "by ANZSIC industry. Sources: "
    "[ABS 8165.0](https://www.abs.gov.au/statistics/economy/business-indicators/"
    "counts-australian-businesses-including-entries-and-exits/latest-release) "
    "and "
    "[ABS 8155.0](https://www.abs.gov.au/statistics/industry/industry-overview/"
    "australian-industry/latest-release). "
    "Use the sidebar to filter by division."
)

# ── Load all datasets ─────────────────────────────────────────────────────────

df_div_counts   = load_csv("abs_division_counts.csv")
df_div_survival = load_csv("abs_division_survival.csv")
df_biz_counts   = load_csv("abs_business_counts.csv")
df_emp_dist     = load_csv("abs_employment_dist.csv")
df_wage_share   = load_csv("abs_wage_share.csv")

if any(d.empty for d in [df_div_counts, df_div_survival, df_biz_counts, df_emp_dist, df_wage_share]):
    st.info(
        "Some data files are missing. Run `python fetch_abs_business_data.py` "
        "to generate them.",
        icon="ℹ️",
    )

# ── Tabs ──────────────────────────────────────────────────────────────────────

tab1, tab2, tab3, tab4 = st.tabs([
    "📈 Business Counts",
    "🏢 Firm Size Structure",
    "🔄 Survival & Turnover",
    "💼 Labour Share",
])

# ═══════════════════════════════════════════════════════════════════════════════
# TAB 1 — Business Counts (division level, 2022–2025)
# Source: abs_division_counts.csv
# ═══════════════════════════════════════════════════════════════════════════════

with tab1:
    st.subheader("Business Counts by Division (ABS 8165.0, 2022–2025)")
    st.markdown(
        "Total number of actively trading businesses at end of financial year, "
        "by ANZSIC division.  Covers four years of data (2021-22 to 2024-25).  "
        "**Note:** a high firm count does not mean a competitive market — "
        "a division can have many small firms alongside a few large dominant ones."
    )

    if df_div_counts.empty:
        st.info("No division count data found. Run the fetch script to populate this.")
    else:
        df_dc = df_div_counts.copy()
        if active_div:
            df_dc = df_dc[df_dc["division"] == active_div]

        latest_yr = int(df_dc["year"].max())
        df_latest = df_dc[df_dc["year"] == latest_yr].sort_values("op_end", ascending=True)

        if active_div:
            # Single division — show trend line
            fig = px.line(
                df_dc.sort_values("year"),
                x="year", y="op_end",
                markers=True,
                title=f"Total Businesses — {active_div}",
                labels={"op_end": "Businesses at year-end", "year": "Year"},
            )
            fig.update_layout(yaxis_tickformat=",")
            st.plotly_chart(fig, use_container_width=True)

            # Also show entry/exit rates over time
            st.markdown("**Entry and exit rates over time (%)**")
            fig2 = px.line(
                df_dc.sort_values("year"),
                x="year", y=["entry_rate", "exit_rate"],
                markers=True,
                title=f"Entry & Exit Rates — {active_div}",
                labels={"value": "Rate (%)", "year": "Year", "variable": ""},
            )
            st.plotly_chart(fig2, use_container_width=True)

        else:
            # All divisions — horizontal bar for latest year
            fig = px.bar(
                df_latest,
                x="op_end", y="division",
                orientation="h",
                title=f"Total Businesses by Division (FY {latest_yr-1}-{str(latest_yr)[2:]})",
                labels={"op_end": "Businesses at year-end", "division": ""},
                color="op_end", color_continuous_scale="Blues",
            )
            fig.update_layout(xaxis_tickformat=",", coloraxis_showscale=False, height=600)
            st.plotly_chart(fig, use_container_width=True)

            # Entry vs exit rate scatter
            st.markdown("**Entry rate vs exit rate by division (latest year)**")
            fig2 = px.scatter(
                df_latest,
                x="entry_rate", y="exit_rate",
                text="division",
                title=f"Contestability Map — Entry vs Exit Rate (FY {latest_yr-1}-{str(latest_yr)[2:]})",
                labels={"entry_rate": "Entry rate (%)", "exit_rate": "Exit rate (%)"},
                size="op_end", size_max=30,
            )
            fig2.update_traces(textposition="top center", textfont_size=9)
            # Reference line y=x (equal entry/exit)
            fig2.add_shape(type="line", x0=0, y0=0, x1=35, y1=35,
                           line=dict(dash="dot", color="grey"))
            fig2.update_layout(height=550)
            st.plotly_chart(fig2, use_container_width=True)
            st.caption("Dot size = number of businesses. Points above the diagonal → more exits than entries.")

    with st.expander("ℹ️ How to interpret this"):
        st.markdown("""
**Entry rate** = new businesses as % of businesses operating at start of year.
**Exit rate** = businesses that ceased trading as % of those at start.

A high entry rate suggests low barriers to entry — new competitors can get in easily.
A persistently *low* entry rate warrants investigation: it may signal regulatory,
capital, or incumbent-advantage barriers.

Points close to the y=x diagonal have roughly balanced entry and exit (steady state).
Points well above it are losing firms faster than they're gaining them.
        """)

# ═══════════════════════════════════════════════════════════════════════════════
# TAB 2 — Firm Size Structure (ANZSIC class level, 2024 & 2025)
# Source: abs_employment_dist.csv
# ═══════════════════════════════════════════════════════════════════════════════

with tab2:
    st.subheader("Firm Size Structure by ANZSIC Class (ABS 8165.0)")
    st.markdown(
        "Breakdown of businesses by employment size band: "
        "**Non-employing** (sole traders), **1–4**, **5–19**, **20–199**, **200+** employees. "
        "Data is at the 4-digit ANZSIC *class* level (the most granular available in 8165.0), "
        "covering June 2024 and June 2025."
    )

    if df_emp_dist.empty:
        st.info("No employment distribution data found. Run the fetch script to populate this.")
    else:
        df_ed = df_emp_dist.copy()
        latest_yr = int(df_ed["year"].max())
        df_ed_latest = df_ed[df_ed["year"] == latest_yr].copy()

        # Search / filter by class name
        search = st.text_input("🔍 Filter by class name (e.g. 'retail', 'construc', 'medical')",
                               placeholder="Leave blank to show top 30 by firm count")
        if search.strip():
            df_ed_latest = df_ed_latest[
                df_ed_latest["anzsic_class_name"].str.contains(search.strip(), case=False, na=False)
            ]
        else:
            df_ed_latest = df_ed_latest.nlargest(30, "total_businesses")

        if df_ed_latest.empty:
            st.info("No classes match your search.")
        else:
            size_cols   = ["non_employing", "emp_1_4", "emp_5_19", "emp_20_199", "emp_200plus"]
            size_labels = {
                "non_employing": "Non-employing",
                "emp_1_4":       "1–4 employees",
                "emp_5_19":      "5–19 employees",
                "emp_20_199":    "20–199 employees",
                "emp_200plus":   "200+ employees",
            }

            df_melt = df_ed_latest.melt(
                id_vars=["anzsic_class_code", "anzsic_class_name", "year"],
                value_vars=size_cols,
                var_name="size_band", value_name="count",
            )
            df_melt["size_label"] = df_melt["size_band"].map(size_labels)
            # Preserve size order
            size_order = list(size_labels.values())
            df_melt["size_label"] = pd.Categorical(df_melt["size_label"],
                                                   categories=size_order, ordered=True)
            df_melt = df_melt.sort_values(["anzsic_class_name", "size_label"])

            view = st.radio("View", ["Count", "% share"], horizontal=True)

            if view == "Count":
                fig = px.bar(
                    df_melt,
                    x="anzsic_class_name", y="count", color="size_label",
                    category_orders={"size_label": size_order},
                    title=f"Employment Size Breakdown — {len(df_ed_latest)} classes (June {latest_yr})",
                    labels={"count": "Businesses", "anzsic_class_name": "",
                            "size_label": "Size band"},
                    color_discrete_sequence=px.colors.sequential.Blues[1:],
                )
                fig.update_layout(yaxis_tickformat=",")
            else:
                # Compute % within each class
                tot = df_ed_latest.set_index("anzsic_class_code")[size_cols].sum(axis=1)
                df_pct = df_ed_latest.copy()
                for col in size_cols:
                    df_pct[col] = (df_pct[col] / tot.reindex(df_pct["anzsic_class_code"]).values * 100).round(1)
                df_pct_melt = df_pct.melt(
                    id_vars=["anzsic_class_code", "anzsic_class_name"],
                    value_vars=size_cols, var_name="size_band", value_name="pct",
                )
                df_pct_melt["size_label"] = df_pct_melt["size_band"].map(size_labels)
                df_pct_melt["size_label"] = pd.Categorical(
                    df_pct_melt["size_label"], categories=size_order, ordered=True)
                df_pct_melt = df_pct_melt.sort_values(["anzsic_class_name", "size_label"])
                fig = px.bar(
                    df_pct_melt,
                    x="anzsic_class_name", y="pct", color="size_label",
                    category_orders={"size_label": size_order},
                    title=f"Employment Size Share — {len(df_ed_latest)} classes (June {latest_yr})",
                    labels={"pct": "% of businesses", "anzsic_class_name": "",
                            "size_label": "Size band"},
                    color_discrete_sequence=px.colors.sequential.Blues[1:],
                )
                fig.update_layout(yaxis_range=[0, 100])

            fig.update_xaxes(tickangle=45)
            fig.update_layout(height=500, legend_title="Size band")
            st.plotly_chart(fig, use_container_width=True)

            with st.expander("📋 Show data table"):
                show_cols = ["anzsic_class_code", "anzsic_class_name", "year",
                             "non_employing", "emp_1_4", "emp_5_19", "emp_20_199",
                             "emp_200plus", "total_businesses"]
                st.dataframe(df_ed_latest[show_cols].sort_values("total_businesses", ascending=False),
                             use_container_width=True)

    with st.expander("ℹ️ How to interpret this"):
        st.markdown("""
Most Australian industries are dominated by **non-employing** businesses (sole traders
and self-employed) and micro-firms (1–4 employees).  This is typical and expected.

A class with an unusually **high share of large firms** may indicate structural
concentration — though you'd need revenue/turnover data to confirm market power.

A trend towards **fewer micro firms** and **more medium/large** over time can be an
early signal of consolidation pressure (use the 2024 vs 2025 toggle to check).

Regulatory compliance costs are generally proportionally higher for smaller firms
(fixed costs spread over less revenue), so size structure affects regulatory burden estimates.
        """)

# ═══════════════════════════════════════════════════════════════════════════════
# TAB 3 — Survival & Turnover (division level, June 2021 cohort)
# Source: abs_division_survival.csv + abs_division_counts.csv
# ═══════════════════════════════════════════════════════════════════════════════

with tab3:
    st.subheader("Business Survival & Turnover (ABS 8165.0)")
    st.markdown(
        "**Survival rates** track the June 2021 cohort — what % of businesses "
        "operating at June 2021 were still operating 1, 2, 3, and 4 years later. "
        "**Entry/exit rates** are annual, covering 2022–2025."
    )

    if df_div_survival.empty or df_div_counts.empty:
        st.info("Survival data not found. Run the fetch script.")
    else:
        df_surv = df_div_survival.copy()
        df_cnt  = df_div_counts.copy()

        if active_div:
            df_surv = df_surv[df_surv["division"] == active_div]
            df_cnt  = df_cnt[df_cnt["division"] == active_div]

        # ── Survival curve ────────────────────────────────────────────────────
        surv_rate_cols = ["surv_rate_1yr", "surv_rate_2yr", "surv_rate_3yr", "surv_rate_4yr"]
        if all(c in df_surv.columns for c in surv_rate_cols):
            df_s_melt = df_surv.melt(
                id_vars=["division"],
                value_vars=surv_rate_cols,
                var_name="period", value_name="survival_pct",
            )
            df_s_melt["years"] = df_s_melt["period"].str.extract(r"(\d+)yr").astype(int)

            if active_div:
                fig = px.line(
                    df_s_melt.sort_values("years"),
                    x="years", y="survival_pct",
                    markers=True,
                    title=f"4-Year Survival Curve — {active_div} (June 2021 cohort)",
                    labels={"years": "Years since June 2021", "survival_pct": "% surviving"},
                )
            else:
                fig = px.line(
                    df_s_melt.sort_values(["division", "years"]),
                    x="years", y="survival_pct",
                    color="division", markers=True,
                    title="4-Year Survival Curves — All Divisions (June 2021 cohort)",
                    labels={"years": "Years since June 2021", "survival_pct": "% surviving",
                            "division": "Division"},
                )
                fig.update_layout(legend_title="Division")

            fig.update_layout(xaxis=dict(tickvals=[1, 2, 3, 4]),
                              yaxis_range=[0, 100], height=480)
            st.plotly_chart(fig, use_container_width=True)

        # ── Entry/exit rate trend ─────────────────────────────────────────────
        st.markdown("**Entry and exit rates over time (%)**")
        if not df_cnt.empty:
            if active_div:
                fig2 = px.line(
                    df_cnt.sort_values("year"),
                    x="year", y=["entry_rate", "exit_rate"],
                    markers=True,
                    title=f"Entry & Exit Rates — {active_div}",
                    labels={"value": "Rate (%)", "year": "Year", "variable": ""},
                )
            else:
                latest_yr = int(df_cnt["year"].max())
                df_latest = df_cnt[df_cnt["year"] == latest_yr].sort_values("entry_rate", ascending=True)
                col1, col2 = st.columns(2)
                with col1:
                    fig2 = px.bar(
                        df_latest,
                        x="entry_rate", y="division", orientation="h",
                        title=f"Entry Rate by Division (FY {latest_yr-1}-{str(latest_yr)[2:]})",
                        labels={"entry_rate": "Entry rate (%)", "division": ""},
                        color="entry_rate", color_continuous_scale="Greens",
                    )
                    fig2.update_layout(coloraxis_showscale=False, height=520)
                    st.plotly_chart(fig2, use_container_width=True)
                with col2:
                    df_ex = df_cnt[df_cnt["year"] == latest_yr].sort_values("exit_rate", ascending=True)
                    fig3 = px.bar(
                        df_ex,
                        x="exit_rate", y="division", orientation="h",
                        title=f"Exit Rate by Division (FY {latest_yr-1}-{str(latest_yr)[2:]})",
                        labels={"exit_rate": "Exit rate (%)", "division": ""},
                        color="exit_rate", color_continuous_scale="Reds",
                    )
                    fig3.update_layout(coloraxis_showscale=False, height=520)
                    st.plotly_chart(fig3, use_container_width=True)
                fig2 = None  # already rendered above for the "all" case

            if active_div and fig2 is not None:
                st.plotly_chart(fig2, use_container_width=True)

    with st.expander("ℹ️ How to interpret this"):
        st.markdown("""
**Survival rates** show what % of firms from the June 2021 cohort survived each year.
A **low 4-year survival rate** often indicates intense competition — or simply a difficult
operating environment (high costs, regulatory burden, cyclical demand).

A **high survival rate** is *not necessarily* a sign of healthy competition.  It can
indicate incumbency protection, high barriers that stop weaker firms from exiting cleanly,
or capital-intensive industries where firms persist even when unprofitable.

**The trend in entry rates over time matters most:** a persistent *decline* in entry rates
in an industry is a warning signal worth investigating for policy purposes.
        """)

# ═══════════════════════════════════════════════════════════════════════════════
# TAB 4 — Labour Share (subdivision level, 2022–2024)
# Source: abs_wage_share.csv
# ═══════════════════════════════════════════════════════════════════════════════

with tab4:
    st.subheader("Labour Share of Industry Value Added (ABS 8155.0)")
    st.markdown(
        "**Labour share = wages & salaries ÷ industry value added (IVA).**  "
        "A *declining* labour share over time is one soft indicator that profits are "
        "capturing a larger share of value added — consistent with weakening competitive "
        "pressure, but also explainable by automation, capital deepening, or industry mix changes.  "
        "Data covers 81 ANZSIC subdivisions across three years (2021-22 to 2023-24)."
    )

    if df_wage_share.empty:
        st.info("No wage share data found. Run the fetch script.")
    else:
        df_ws = df_wage_share.copy()
        if active_div:
            df_ws = df_ws[df_ws["division"].str.lower() == active_div.lower()]

        if df_ws.empty:
            st.info(f"No wage share data for {active_div}.")
        else:
            latest_yr = int(df_ws["year"].max())
            df_latest = df_ws[df_ws["year"] == latest_yr].sort_values("labour_share_pct")

            col1, col2 = st.columns([3, 1])
            with col1:
                fig = px.bar(
                    df_latest,
                    x="labour_share_pct", y="subdivision_name",
                    orientation="h",
                    title=f"Labour Share by Subdivision — FY {latest_yr-1}-{str(latest_yr)[2:]}",
                    labels={"labour_share_pct": "Labour share (%)", "subdivision_name": ""},
                    color="labour_share_pct",
                    color_continuous_scale="RdYlGn",
                    range_color=[0, 100],
                )
                fig.add_vline(x=50, line_dash="dot", line_color="grey",
                              annotation_text="50%")
                fig.update_layout(coloraxis_showscale=True, height=max(400, len(df_latest) * 22))
                st.plotly_chart(fig, use_container_width=True)

            with col2:
                st.markdown("**Summary**")
                avg = df_latest["labour_share_pct"].mean()
                st.metric("Average", f"{avg:.1f}%")
                hi = df_latest.nlargest(3, "labour_share_pct")
                lo = df_latest.nsmallest(3, "labour_share_pct")
                st.markdown("**Highest**")
                for _, r in hi.iterrows():
                    st.markdown(f"- {r['subdivision_name']}: {r['labour_share_pct']:.0f}%")
                st.markdown("**Lowest**")
                for _, r in lo.iterrows():
                    st.markdown(f"- {r['subdivision_name']}: {r['labour_share_pct']:.0f}%")

            # ── Trend over time ────────────────────────────────────────────────
            st.markdown("---")
            st.markdown("**Labour share trend over time**")

            # Pick subdivisions to show — top 10 by latest share if "All"
            if active_div:
                df_trend = df_ws.sort_values(["subdivision_name", "year"])
                colour_col = "subdivision_name"
            else:
                top_subdivs = df_latest.nlargest(10, "labour_share_pct")["subdivision_name"].tolist()
                df_trend = df_ws[df_ws["subdivision_name"].isin(top_subdivs)].sort_values("year")
                colour_col = "subdivision_name"

            fig2 = px.line(
                df_trend, x="year", y="labour_share_pct",
                color=colour_col, markers=True,
                title="Labour Share Trend by Subdivision",
                labels={"labour_share_pct": "Labour share (%)", "year": "Year",
                        colour_col: "Subdivision"},
            )
            fig2.add_hline(y=50, line_dash="dot", line_color="grey",
                           annotation_text="50% reference")
            fig2.update_layout(yaxis_range=[0, 100], height=460, legend_title="Subdivision")
            st.plotly_chart(fig2, use_container_width=True)

            if not active_div:
                st.caption("Showing top 10 subdivisions by labour share. Select a division in the sidebar to see all subdivisions in that industry.")

            with st.expander("📋 Show data table"):
                show_cols = ["division", "subdivision_code", "subdivision_name", "year",
                             "wages_m", "iva_m", "employment_000", "labour_share_pct"]
                st.dataframe(
                    df_ws[show_cols].sort_values(["subdivision_name", "year"]),
                    use_container_width=True,
                )

    with st.expander("ℹ️ How to interpret this"):
        st.markdown("""
**Labour share = wages / industry value added.**

In a competitive market, firms compete for workers (which pushes up wages) and compete
for customers (which compresses margins).  Both forces tend to sustain labour's share of value.

Where firms have **market power**, they may suppress wages relative to profits — contributing
to a *falling* labour share over time.  This is one of several soft indicators used by
competition economists alongside concentration ratios, mark-up analysis, and entry/exit data.

**Important caveats:**
- A *low* labour share is not proof of a competition problem.  Mining and energy have
  structurally low shares because they are capital-intensive, not because of monopoly.
- A *falling* share can reflect automation (fewer workers needed) or outsourcing
  (shifts to contractor income not captured in wages data).
- Use this alongside other indicators — never in isolation.
        """)

# ── Footer ────────────────────────────────────────────────────────────────────

st.markdown("---")
st.caption(
    "Data: ABS 8165.0 (Counts of Australian Businesses, June 2021–2025) and "
    "ABS 8155.0 (Australian Industry, 2023-24).  "
    "Run `python fetch_abs_business_data.py` to refresh from local ABS Data Manual/ files."
)
